### ISSUE TITLE
error in jszip-load.js

### ISSUE THREAD

**Issue by sangari** [logiclord/epubReader#14]
hai,

 i have used your file  but i got an 
Error: End of stream reached (stream length = 401272, asked index = 458090). Corrupted zip ? in jszip-load.js
pls help me.

**Comment by sangari** [comment]
hai,
i got working by adding mimetype in xhr request.
xhr.overrideMimeType("text/plain; charset=x-user-defined");

**Comment by logiclord** [comment]
Can provide some more details ? Which epub file you tried to use ? Did you followed setup guide ?
