### ISSUE TITLE
Bookmark in epub.js

### ISSUE THREAD

**Issue by sangari** [logiclord/epubReader#15]
hai ,

 can you pls explain me to implement bookmark in https://github.com/logiclord/epubjs.

**Comment by logiclord** [comment]
Hi sangari,

Basic logic that I used in epubReader Bookmarks is Identifier and Position

https://github.com/logiclord/epubReader/blob/master/js/epubReaderNavigator.js#L443 

I create a unique Identifier and wrap it around the bookmarked text using html tag. This way I am able to identify bookmarks. I also replicate a part of HTML from bookmarked text for preview.

--logiclord
