### ISSUE TITLE
ePub Reader viewer is totally based on "toc.ncx" content

### ISSUE THREAD

**Issue by dghag** [logiclord/epubReader#18]
When all html pages are included in the "toc.ncx" that time only it shows all included pages, otherwise if "toc.ncx" is empty then it showing "0" results. It is very bad thing. I want to the viewer which is based on "content.opf".

**Comment by logiclord** [comment]
We assumed that table of content is available in toc.ncx file. We can modify https://github.com/logiclord/epubReader/blob/master/js/epubReader.js#L131 method to read and parse "content.opf" for getting table of content.
