### ISSUE TITLE
Reader not reads "ePub" placed on other server

### ISSUE THREAD

**Issue by dghag** [logiclord/epubReader#19]
I try to get "ePub" located on other server. It always shows me "Failed to get file + url" error. Why this happening? Is there any cross domain request issue? How to solve this problem?

**Comment by logiclord** [comment]
Yes, this is due to cross domain request.

**Comment by dghag** [comment]
How to solve this problem?

**Comment by logiclord** [comment]
You need to modify https://github.com/logiclord/epubReader/blob/master/js/epubReaderFileFacilitator.js#L290

**Comment by dghag** [comment]
Yeah, I knew it. But can you please tell me what should I modify?

**Comment by logiclord** [comment]
If you have control over other server then you can explicitly allow in headers otherwise you have to use something like  jQuery ajax.

**Comment by dghag** [comment]
I don't have any control on other server, so I have to go with second option i.e jquery AJAX. I don't have enough idea about it. So can you please paste the changes here?

**Comment by logiclord** [comment]
I think you can use something like http://api.jquery.com/jQuery.ajax/ for cross domain request but please do note that it is possible for other server to deny your request.

**Comment by dghag** [comment]
What should I do to avoid deny request?

How should I add jquery AJAX request in below code:

that.getEpubFile = function (url) {
            var request = useMSXHR() ? new ActiveXObject('Msxml2.XmlHttp.6.0') : new XMLHttpRequest();
            request.onreadystatechange = function () {
                if (request.readyState === 1) {
                    if (request.overrideMimeType) {
                        request.overrideMimeType('text/plain; charset=x-user-defined');
                    }
                    request.send();
                }

```
            if (request.readyState === 4) {
                if (request.status === 200) {
                    var data, j;
                    if (useMSXHR()) {
                        data = new VBArray(request.responseBody).toArray();
                        for (j = 0; j < data.length; j = j + 1) {
                            data[j] = String.fromCharCode(data[j]);
                        }
                        that.JSZipWrapper.epubLoad(data.join(''));
                        that.events.afterEpubReady.fire();
                        request.abort();
                    } else {
                        that.JSZipWrapper.epubLoad(request.responseText);
                        that.events.afterEpubReady.fire();
                    }
                } else {
                    epubReaderErrors.XHRException('Failed to get file ' + url);
                    return null;
                }
            }
        };
        request.open('GET', url, true);
    }; 
```

**Comment by logiclord** [comment]
Get epub file content in a variable and then continue on same process by using that.JSZipWrapper.epubLoad then that.events.afterEpubReady.fire(). There is no straight forward way to escape deny request that's why cross domain requests are considered as security issue.
